topic:
 cmd_vel: /coconut_vel
 odom: /odom_gz

service:
 name: test

frame:
 odom: odom_gz
 base_footprint: base_footprint

control:
 distance_goal_tolerance: 0.01 #linear 
 heading_tolerance: 0.01 #angular
 yaw_goal_tolerance: 0.005 #angular

 linear_velocity_max: 0.09 #linear
 angular_velocity_max: 0.5 #angular

 kp: 1.2 #angular
 kp_linear: 0.4 #linear

 palabola_params:
  alpha: 0.1

docking:
 delay_before_start: 0.5 #sec [warning: delay time must >= 0.5]
 first_pre_docking_distance: 0.9 #meters
 docking_distance: 0.38 #meters
 first_docking_tolerance: 0.05 #meters

